services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: build/auth.Dockerfile
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    env_file:
      - .env
    depends_on:
      postgres_auth:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres_auth:
    container_name: postgres_auth_service
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_AUTH_PORT}:5432
    command:
      - "postgres"
      - "-c"
      - "port=5432"
    volumes:
      - postgres_auth:/var/lib/postgresql/data
      - ./init/auth.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    container_name: redis
    image: redis:7.2.5
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/root/redis/
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES_NUM}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  minio:
    container_name: minio
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data/
    volumes:
      - s3_data:/data
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 5s
      retries: 3

  postgres_file:
    container_name: postgres_file_service
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_FILE_PORT}:5432
    command:
      - "postgres"
      - "-c"
      - "port=5432"
    volumes:
      - postgres_file:/var/lib/postgresql/data
      - ./init/file.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  file:
    container_name: file
    build:
      context: .
      dockerfile: build/file.Dockerfile
    ports:
      - ${FILE_PORT}:${FILE_PORT}
    env_file:
      - .env
    depends_on:
      postgres_file:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  postgres_auth:
  postgres_file:
  redis:
  redis_data:
  s3_data:
